### ISSUE TITLE
Build not working properly

### ISSUE THREAD

**Issue by sahlouls** [mgechev/angular2-ngc-rollup-build#1]
λ npm run ngc

> angular2-min@1.0.0 ngc d:\my_repos\angular2-ngc-rollup-build
> ngc -p . && cp app/\* compiled

can't resolve module @angular/core/src/di/opaque_token from d:\my_repos\angular2-ngc-rollup-build\index.ts
Error: Could not resolve module @angular/core/src/di/opaque_token relative to d:\my_repos\angular2-ngc-rollup-build\index.ts
    at ReflectorHost.findDeclaration (D:\my_repos\angular2-ngc-rollup-build\node_modules\@angular\compiler-cli\src\reflector_host.js:96:23)
    at StaticReflector.initializeConversionMap (D:\my_repos\angular2-ngc-rollup-build\node_modules\@angular\compiler-cli\src\static_reflector.js:133:38)
    at new StaticReflector (D:\my_repos\angular2-ngc-rollup-build\node_modules\@angular\compiler-cli\src\static_reflector.js:34:14)
    at Function.CodeGenerator.create (D:\my_repos\angular2-ngc-rollup-build\node_modules\@angular\compiler-cli\src\codegen.js:134:31)
    at codegen (D:\my_repos\angular2-ngc-rollup-build\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (D:\my_repos\angular2-ngc-rollup-build\node_modules\@angular\tsc-wrapped\src\main.js:25:16)
    at Object.<anonymous> (D:\my_repos\angular2-ngc-rollup-build\node_modules\@angular\compiler-cli\src\main.js:12:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
Compilation failed

**Comment by Destreyf** [comment]
I am also seeing this issue under windows on my side.

Running this under Ubuntu (Windows Subsystem for Linux) it builds as intended.

**Comment by ghostofcain** [comment]
+1. Same error on Windows. Haven't tried in Debian.

**Comment by StephenEdginton** [comment]
Same Issue

**Comment by Destreyf** [comment]
This sample is quite a bit out of date, i would highly recommend trying using the Angular-cli and this method https://github.com/brandonroberts/router-cli-aot i instaleld "@angular/compiler-cli" and then added the run command out of the package.json and created "main-static.ts" and changed the "angular-build.json" to target "main-static.ts" instead of "main.ts" and its working for my projects so far.

**Comment by mgechev** [comment]
This is only a demo for the blog post, the repository is not intended to be used in production. A production ready starter can be found [here](https://github.com/mgechev/angular2-seed).
