### ISSUE TITLE
Build broken (macos)

### ISSUE THREAD

**Issue by SekibOmazic** [mgechev/angular2-ngc-rollup-build#3]
Here is my npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build_prod' ]
2 info using npm@3.10.3
3 info using node@v6.3.0
4 verbose run-script [ 'prebuild_prod', 'build_prod', 'postbuild_prod' ]
5 info lifecycle angular2-min@1.0.0~prebuild_prod: angular2-min@1.0.0
6 silly lifecycle angular2-min@1.0.0~prebuild_prod: no script for prebuild_prod, continuing
7 info lifecycle angular2-min@1.0.0~build_prod: angular2-min@1.0.0
8 verbose lifecycle angular2-min@1.0.0~build_prod: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-min@1.0.0~build_prod: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/sekibomazic/Documents/projects/fcb/angular2-ngc-rollup-build/node_modules/.bin:/usr/local/Cellar/node/6.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle angular2-min@1.0.0~build_prod: CWD: /Users/sekibomazic/Documents/projects/fcb/angular2-ngc-rollup-build
11 silly lifecycle angular2-min@1.0.0~build_prod: Args: [ '-c',
11 silly lifecycle   'npm run clean && npm run ngc && npm run build && npm run rollup && npm run es5 && npm run minify' ]
12 silly lifecycle angular2-min@1.0.0~build_prod: Returned: code: 1  signal: null
13 info lifecycle angular2-min@1.0.0~build_prod: Failed to exec build_prod script
14 verbose stack Error: angular2-min@1.0.0 build_prod: `npm run clean && npm run ngc && npm run build && npm run rollup && npm run es5 && npm run minify`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-min@1.0.0
16 verbose cwd /Users/sekibomazic/Documents/projects/fcb/angular2-ngc-rollup-build
17 error Darwin 15.5.0
18 error argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "build_prod"
19 error node v6.3.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error angular2-min@1.0.0 build_prod: `npm run clean && npm run ngc && npm run build && npm run rollup && npm run es5 && npm run minify`
22 error Exit status 1
23 error Failed at the angular2-min@1.0.0 build_prod script 'npm run clean && npm run ngc && npm run build && npm run rollup && npm run es5 && npm run minify'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-min package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean && npm run ngc && npm run build && npm run rollup && npm run es5 && npm run minify
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-min
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-min
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by SekibOmazic** [comment]
OK will close this as running `npm run build_prod` is still failing but running each step separately works.
