### ISSUE TITLE
Unable to compile any more complex template

### ISSUE THREAD

**Issue by k3a** [mgechev/angular2-ngc-rollup-build#5]
Hi, thanks for the nice blogpost mentioning NGC.

There is a problem though. Once you make a more complicated template with directives and bindings, NGS is totally lost. Maybe we need to do something like register all directives manually?

Just try to put this to app.component.ts:

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `Hi. <i (click)="onClick()">Click</i><div *ngIf="isShown">Shown</div>`
})
export class AppComponent {
    isShown = false;

    onClick() {
        this.isShown = !this.isShown;
    }
}
```

and NGC will fail with this:

```
> ngc -p . && cp app/* compiled

Error: Template parse errors:
Can't bind to 'ngIf' since it isn't a known native property ("Hi. <i (click)="onClick()">Click</i><div [ERROR ->]*ngIf="isShown">Shown</div>"): AppComponent@0:41
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("Hi. <i (click)="onClick()">Click</i>[ERROR ->]<div *ngIf="isShown">Shown</div>"): AppComponent@0:36
    at new BaseException (/private/tmp/angular2-ngc-rollup-build/node_modules/@angular/compiler/src/facade/exceptions.js:27:23)
    at TemplateParser.parse (/private/tmp/angular2-ngc-rollup-build/node_modules/@angular/compiler/src/template_parser.js:95:19)
    at OfflineCompiler._compileComponent (/private/tmp/angular2-ngc-rollup-build/node_modules/@angular/compiler/src/offline_compiler.js:92:51)
    at /private/tmp/angular2-ngc-rollup-build/node_modules/@angular/compiler/src/offline_compiler.js:74:44
    at Array.forEach (native)
    at OfflineCompiler.compileTemplates (/private/tmp/angular2-ngc-rollup-build/node_modules/@angular/compiler/src/offline_compiler.js:66:20)
    at /private/tmp/angular2-ngc-rollup-build/node_modules/@angular/compiler-cli/src/codegen.js:46:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
```

So it is basically unusable for anything else than a static template.

**Comment by k3a** [comment]
Alright. (at least at the moment) Directives needs to be manually referenced.

```
import { Component } from '@angular/core';
import {NgIf} from '@angular/common';

@Component({
  selector: 'my-app',
  template: `Hi. <i (click)="onClick()">Click</i><div *ngIf="isShown">Shown</div>`,
  directives: [NgIf]
})
export class AppComponent {
    isShown = false;

    onClick() {
        this.isShown = !this.isShown;
    }
}
```

If you or others are interested in more, see @angular/compiler-cli integration test sample https://github.com/angular/angular/tree/master/modules/%40angular/compiler-cli/integrationtest/src .
