### ISSUE TITLE
Could not resolve entry (dist/main-prod.js)

### ISSUE THREAD

**Issue by visitsb** [mgechev/angular2-ngc-rollup-build#9]
Any idea why adding *ngFor directive causes below error? 

```
> rollup -f iife -c rollup.config.js -o dist/bundle.es2015.js

Could not resolve entry (dist/main-prod.js)
Error: Could not resolve entry (dist/main-prod.js)
    at /angular2-ngc-rollup-build/node_modules/rollup/src/Bundle.js:109:29
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Removing the *ngFor works, why?

My changed code for `app.component.ts` is below
```
import { Component } from '@angular/core';

@Component({
    selector: 'my-app',
    template: `
        <h2>Hello world!</h2>
        <div *ngFor="let id of ids">
            {{id}}
        </div>
    `
})
export class AppComponent {
    ids:Number[]= [ 1, 2, 3, 4, 5];
}
```

**Comment by mgechev** [comment]
AoT needs to be run before rollup.
